# Generated by Django 2.2.6 on 2020-09-08 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrollnum', models.CharField(blank=True, max_length=10, verbose_name='Enrollment Number')),
                ('currentyear', models.SmallIntegerField(help_text='Course Year', verbose_name='Course Year')),
                ('sem', models.SmallIntegerField(help_text='Semester', verbose_name='Semester')),
                ('classsnum', models.SmallIntegerField(help_text='Class Serial Number', verbose_name='Class Serial Number')),
            ],
        ),
    ]
