# Generated by Django 2.2.6 on 2020-09-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.SmallIntegerField(choices=[(1, 'Bachelors of Technology (IT)'), (2, 'Bachelors of Technology (CSE)'), (3, 'Bachelors of Technology (ECE)'), (4, 'Bachelors of Technology (EEE)'), (5, 'Bachelors of Technology (CSE Second Shift)'), (6, 'Bachelors of Technology (IT Second Shift)'), (7, 'Bachelors of Technology (ECE Second Shift)')], help_text='Course Name', verbose_name='Course Name')),
                ('duration_year', models.SmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], help_text='Course duration', verbose_name='Course duration')),
                ('duration_semester', models.SmallIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester'), (4, 'Fourth Semester'), (5, 'Fifth Semester'), (6, 'Sixth Semester'), (7, 'Seventh Semester'), (8, 'Eighth Semester')], help_text='Semester in courses', verbose_name='Semester in courses')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.SmallIntegerField(verbose_name='Section number')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classsnum',
            new_name='serialnum',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.AddField(
            model_name='student',
            name='currentsem',
            field=models.SmallIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester'), (4, 'Fourth Semester'), (5, 'Fifth Semester'), (6, 'Sixth Semester'), (7, 'Seventh Semester'), (8, 'Eighth Semester')], default=7, help_text='Semester', verbose_name='Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='currentyear',
            field=models.SmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], help_text='Course Year', verbose_name='Course Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollnum',
            field=models.BigIntegerField(blank=True, verbose_name='Enrollment Number'),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], verbose_name='Year of Subject')),
                ('sem', models.SmallIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester'), (4, 'Fourth Semester'), (5, 'Fifth Semester'), (6, 'Sixth Semester'), (7, 'Seventh Semester'), (8, 'Eighth Semester')], verbose_name='Semester of Subject')),
                ('name', models.CharField(max_length=50, verbose_name='Subject name')),
                ('type', models.SmallIntegerField(choices=[(1, 'Theory'), (2, 'Practical')], verbose_name='Subject Type')),
                ('code_prefix', models.CharField(max_length=2, verbose_name='Code Prefix')),
                ('code_suffix', models.IntegerField(choices=[(2, 'Power Engineering'), (3, 'Mechanical Engineering'), (4, 'Mechatronics'), (5, 'Mechanical and Automation Engineering'), (6, 'Electrical and Electronics Engineering'), (7, 'Electrical Engineering'), (8, 'Information Technology'), (9, 'Computer Science and Engineering'), (10, 'Civil Engineering'), (11, 'Electronics and Communications Engineering'), (12, 'Environmental Engineering'), (13, 'Tool Engineering'), (14, 'Mathematics'), (15, 'Humanities and Social Sciences'), (16, 'Social Services')], verbose_name='Code Suffix')),
                ('codenum', models.IntegerField(verbose_name='Subject Code Number')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Course', verbose_name='Subject of Course(s)')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.PROTECT, to='users.Course', verbose_name='Course Enrolled'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.Section', verbose_name='Section'),
            preserve_default=False,
        ),
    ]
