# Generated by Django 2.2.6 on 2020-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200913_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], verbose_name='Year of Subject')),
                ('sem', models.SmallIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester'), (4, 'Fourth Semester'), (5, 'Fifth Semester'), (6, 'Sixth Semester'), (7, 'Seventh Semester'), (8, 'Eighth Semester')], verbose_name='Semester of Subject')),
                ('name', models.CharField(max_length=50, verbose_name='Subject name')),
                ('type', models.SmallIntegerField(choices=[(1, 'Theory'), (2, 'Practical')], verbose_name='Subject Type')),
                ('code_prefix', models.CharField(max_length=2, verbose_name='Code Prefix')),
                ('code_suffix', models.IntegerField(choices=[(2, 'Power Engineering'), (3, 'Mechanical Engineering'), (4, 'Mechatronics'), (5, 'Mechanical and Automation Engineering'), (6, 'Electrical and Electronics Engineering'), (7, 'Electrical Engineering'), (8, 'Information Technology'), (9, 'Computer Science and Engineering'), (10, 'Civil Engineering'), (11, 'Electronics and Communications Engineering'), (12, 'Environmental Engineering'), (13, 'Tool Engineering'), (14, 'Mathematics'), (15, 'Humanities and Social Sciences'), (16, 'Social Services')], verbose_name='Code Suffix')),
                ('codenum', models.IntegerField(verbose_name='Subject Code Number')),
                ('courses', models.ManyToManyField(to='users.Course', verbose_name='Subject of Course(s)')),
            ],
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
