# Generated by Django 2.2.6 on 2020-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200913_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollnum',
            field=models.BigIntegerField(blank=True, unique=True, verbose_name='Enrollment Number'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code_suffix',
            field=models.IntegerField(choices=[(2, 'Power Engineering'), (3, 'Mechanical Engineering'), (4, 'Mechatronics'), (5, 'Mechanical and Automation Engineering'), (6, 'Electrical and Electronics Engineering'), (7, 'Electrical Engineering'), (8, 'Information Technology'), (9, 'Computer Science and Engineering'), (10, 'Civil Engineering'), (11, 'Electronics and Communications Engineering'), (12, 'Environmental Engineering'), (13, 'Tool Engineering'), (14, 'Mathematics'), (15, 'Humanities and Social Sciences'), (16, 'Social Services'), (17, 'Physics'), (18, 'Chemistry')], verbose_name='Code Suffix'),
        ),
    ]
